<?php

declare(strict_types=1);

// 构建器静态解析 env 占位，运行时值来自进程环境或外部 .env，不把秘密编入产物。
return [
    'name' => env('APP_NAME', 'typeapp'),
    'environment' => env('APP_ENV', 'production'),
    'debug' => env('APP_DEBUG', false),
    'broker' => [
        'listen' => env('BROKER_LISTEN', '127.0.0.1'),
        'port' => env('BROKER_PORT', 8883),
        'node_id' => env('BROKER_NODE_ID', 'default'),
        'io_driver' => env('BROKER_IO_DRIVER', 'swoole'),
        'plaintext' => env('BROKER_PLAINTEXT', false),
        'ws_port' => env('BROKER_WS_PORT', 0),
        'wss_port' => env('BROKER_WSS_PORT', 0),
        'allowed_origins' => env('BROKER_ALLOWED_ORIGINS', ''),
        'certificate' => env('BROKER_CERTIFICATE', ''),
        'private_key' => env('BROKER_PRIVATE_KEY', ''),
        'mtls_port' => env('BROKER_MTLS_PORT', 0),
        'client_ca' => env('BROKER_CLIENT_CA', ''),
        'username' => env('BROKER_CLIENT_USERNAME', ''),
        'password' => env('BROKER_CLIENT_PASSWORD', ''),
        'topic_prefix' => env('BROKER_TOPIC_PREFIX', ''),
        'command' => env('BROKER_COMMAND', ''),
        'standby' => env('BROKER_STANDBY_NAMES', ''),
        'probe_token' => env('BROKER_PROBE_TOKEN', ''),
    ],
    'exports' => [
        'directory' => env('IOT_EXPORT_DIRECTORY', 'storage/exports'),
        'namespace' => env('IOT_EXPORT_NAMESPACE', 'typeapp-iot'),
        'redis_host' => env('IOT_EXPORT_REDIS_HOST', '127.0.0.1'),
        'redis_port' => env('IOT_EXPORT_REDIS_PORT', 6379),
        'redis_username' => env('IOT_EXPORT_REDIS_USERNAME', ''),
        'redis_password' => env('IOT_EXPORT_REDIS_PASSWORD', ''),
        'redis_tls' => env('IOT_EXPORT_REDIS_TLS', false),
        'redis_ca' => env('IOT_EXPORT_REDIS_CA', ''),
    ],
    'mqtt' => [
        'io_driver' => env('IOT_MQTT_IO_DRIVER', 'swoole'),
        'listen' => env('IOT_MQTT_LISTEN', '127.0.0.1'),
        'port' => env('IOT_MQTT_PORT', 8883),
        'ws_port' => env('IOT_MQTT_WS_PORT', 0),
        'wss_port' => env('IOT_MQTT_WSS_PORT', 0),
        'allowed_origins' => env('IOT_MQTT_ALLOWED_ORIGINS', ''),
        'node_id' => env('IOT_MQTT_NODE_ID', 'default'),
        'clustered' => env('IOT_MQTT_CLUSTERED', false),
        'command' => env('IOT_MQTT_COMMAND', ''),
        'certificate' => env('IOT_MQTT_CERTIFICATE', ''),
        'private_key' => env('IOT_MQTT_PRIVATE_KEY', ''),
        'private_key_passphrase' => env('IOT_MQTT_PRIVATE_KEY_PASSPHRASE', ''),
        'mtls_port' => env('IOT_MQTT_MTLS_PORT', 0),
        'client_ca' => env('IOT_MQTT_CLIENT_CA', ''),
        'standby' => env('IOT_MQTT_STANDBY', 'iot_sync'),
        'maximum_connections' => env('IOT_MQTT_MAXIMUM_CONNECTIONS', 10100),
        'maximum_device_connections' => env('IOT_MQTT_MAXIMUM_DEVICE_CONNECTIONS', 10000),
        'maximum_service_connections' => env('IOT_MQTT_MAXIMUM_SERVICE_CONNECTIONS', 100),
        'maximum_sessions' => env('IOT_MQTT_MAXIMUM_SESSIONS', 20000),
        'maximum_pending_messages' => env('IOT_MQTT_MAXIMUM_PENDING_MESSAGES', 2000000),
        'maximum_pending_bytes' => env('IOT_MQTT_MAXIMUM_PENDING_BYTES', 4294967296),
        'maximum_shared_messages' => env('IOT_MQTT_MAXIMUM_SHARED_MESSAGES', 1000000),
        'maximum_shared_bytes' => env('IOT_MQTT_MAXIMUM_SHARED_BYTES', 2147483648),
        'maximum_device_messages' => env('IOT_MQTT_MAXIMUM_DEVICE_MESSAGES', 10000),
        'maximum_device_bytes' => env('IOT_MQTT_MAXIMUM_DEVICE_BYTES', 16777216),
        'maximum_application_messages' => env('IOT_MQTT_MAXIMUM_APPLICATION_MESSAGES', 1000000),
        'maximum_application_bytes' => env('IOT_MQTT_MAXIMUM_APPLICATION_BYTES', 2147483648),
    ],
    'ingestion' => [
        'host' => env('IOT_INGESTION_HOST', '127.0.0.1'),
        'port' => env('IOT_INGESTION_PORT', 8883),
        'instance' => env('IOT_INGESTION_INSTANCE', 'default'),
        'credential_id' => env('IOT_INGESTION_CREDENTIAL_ID', ''),
        'secret_hash' => env('IOT_INGESTION_SECRET_HASH', ''),
        'password' => env('IOT_INGESTION_PASSWORD', ''),
        'ca' => env('IOT_INGESTION_CA', ''),
        'peer_name' => env('IOT_INGESTION_PEER_NAME', ''),
    ],
    'device' => [
        'id' => env('IOT_DEVICE_ID', ''),
        'ownership_id' => env('IOT_DEVICE_OWNERSHIP_ID', ''),
        'tenant_id' => env('IOT_DEVICE_TENANT_ID', ''),
        'model_version' => env('IOT_DEVICE_MODEL_VERSION', 1),
        'supported_models' => env('IOT_DEVICE_SUPPORTED_MODELS', '{}'),
        'credential_id' => env('IOT_DEVICE_CREDENTIAL_ID', ''),
        'password' => env('IOT_DEVICE_PASSWORD', ''),
        'cache' => env('IOT_DEVICE_CACHE', ''),
        'maximum_records' => env('IOT_DEVICE_MAXIMUM_RECORDS', 8640),
        'maximum_bytes' => env('IOT_DEVICE_MAXIMUM_BYTES', 8640000),
        'host' => env('IOT_DEVICE_HOST', '127.0.0.1'),
        'port' => env('IOT_DEVICE_PORT', 8883),
        'ca' => env('IOT_DEVICE_CA', ''),
        'peer_name' => env('IOT_DEVICE_PEER_NAME', ''),
    ],
    'notices' => [
        'redis_host' => env('IOT_NOTICES_REDIS_HOST', '127.0.0.1'),
        'redis_port' => env('IOT_NOTICES_REDIS_PORT', 6379),
        'redis_username' => env('IOT_NOTICES_REDIS_USERNAME', ''),
        'redis_password' => env('IOT_NOTICES_REDIS_PASSWORD', ''),
        'redis_tls' => env('IOT_NOTICES_REDIS_TLS', false),
        'redis_ca' => env('IOT_NOTICES_REDIS_CA', ''),
        'namespace' => env('IOT_NOTICES_NAMESPACE', 'typeapp-iot'),
    ],
    'http' => [
        'listen' => env('APP_LISTEN', '127.0.0.1'),
        'port' => env('APP_PORT', 9501),
        'allowed_hosts' => env('APP_ALLOWED_HOSTS', ''),
        'trusted_proxies' => env('APP_TRUSTED_PROXIES', ''),
        'upload_temp' => env('APP_UPLOAD_TEMP', ''),
    ],
];
