<?php

declare(strict_types=1);

use Type\Orm\DatabaseManager;
use Type\Orm\Db;
use Type\Orm\ModelException;
use Type\Runtime\ExecutionScope;
use TypeApp\ModelExample\Drivers;
use TypeApp\ModelExample\Invoice;

/**
 * 将当前示例的行为断言转为明确失败，避免只输出成功文字而忽略实际状态。
 *
 * @throws \RuntimeException 条件不成立。
 */
function exactExpect(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

/**
 * 验证精确数值、UTC 微秒、部分字段及 null 的三库保存语义。
 *
 * @param list<string> $argv 程序路径与该示例的显式参数。
 */
function main(int $argc, array $argv): void
{
    \Type\Runtime\CoroutineRuntime::run(static function () use ($argv): void {
        $driver = (string) ($argv[1] ?? 'sqlite');
        $database = new DatabaseManager(['default' => Drivers::create($driver)], 1, 0);
        Db::configure($database);
        $scope = new ExecutionScope();
        try {
            $scope->run(static function (ExecutionScope $current) use ($database, &$scope, $argv, $driver): void {
                $connection = Db::connection('default', true);
                $key = $driver === 'mysql' ? 'BIGINT PRIMARY KEY AUTO_INCREMENT'
                    : ($driver === 'pgsql' ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT');
                $amount = $driver === 'sqlite' ? 'TEXT' : 'DECIMAL(30,2)';
                $large = $driver === 'sqlite' ? 'TEXT' : 'DECIMAL(30,0)';
                $date = $driver === 'mysql' ? 'DATETIME(6)' : ($driver === 'pgsql' ? 'TIMESTAMP(6) WITH TIME ZONE' : 'TEXT');
                $connection->raw('CREATE TEMPORARY TABLE type_model_invoices (id ' . $key . ', external_id ' . $large . ' NOT NULL, amount '
                    . $amount . ' NOT NULL, happened_at ' . $date . " NOT NULL, note VARCHAR(255) NULL, internal VARCHAR(255) NOT NULL DEFAULT '')");
                $invoice = new Invoice(['external_id' => '92233720368547758081234567890', 'amount' => '9999999999999999999999999999.99',
                    'happened_at' => '2026-09-09T08:34:56.123456+08:00', 'note' => null, 'internal' => '私有']);
                $invoice->save();
                $id = $invoice->getId();
                $read = Invoice::query()->find($id);
                exactExpect($read->getExternalId() === '92233720368547758081234567890' && $read->getAmount() === '9999999999999999999999999999.99', '金额或大整数丢失精度');
                exactExpect($read->getHappenedAt()->format('Y-m-d\TH:i:s.u\Z') === '2026-09-09T00:34:56.123456Z'
                    && $read->getHappenedAt()->getOffset() === 0, 'UTC 或微秒往返错误');
                $read->setHappenedAt('2026-09-08T20:34:56.123456-04:00');
                exactExpect($read->dirty() === [], '同一时刻被误判为修改');
                $partial = Invoice::query()->select(['amount'])->find($id);
                exactExpect(!$partial->loaded('external_id'), '部分字段被伪装加载');
                $partial->setAmount('-00012.3400');
                $partial->save();
                $current = Invoice::query()->find($id);
                exactExpect($current->getAmount() === '-12.34' && $current->getExternalId() === '92233720368547758081234567890', '规范化或部分更新影响其他列');
                $current->setAmount('-0.0000');
                exactExpect($current->getAmount() === '0.00', '零值规范化错误');
                $mutable = new DateTime('2026-09-09T01:02:03.000004+00:00');
                $current->setHappenedAt($mutable);
                $mutable->modify('+1 day');
                exactExpect($current->getHappenedAt()->format('Y-m-d') === '2026-09-09', '日期保留了外部可变对象');
                $current->save();
                $current->setNote('内容');
                $current->save();
                $current->setNote(null);
                $current->save();
                exactExpect(Invoice::query()->find($id)->getNote() === null, 'null 更新没有保存');
                $output = $current->toArray();
                exactExpect(is_string($output['amount']) && is_string($output['external_id']) && is_string($output['happened_at'])
                    && !isset($output['internal']), '精确字段或安全输出错误');
                foreach ([['amount', '1.234', 'scale_exceeded'], ['amount', '10000000000000000000000000000.00', 'precision_exceeded'],
                    ['amount', 1.2, 'invalid_field_type'], ['external_id', '9999999999999999999999999999999', 'precision_exceeded'],
                    ['external_id', 1.0, 'invalid_field_type'], ['happened_at', '2026-02-30T00:00:00Z', 'invalid_datetime'],
                    ['happened_at', '2026-09-09 01:02:03', 'invalid_datetime']] as [$field, $value, $code]) {
                    $rejected = false;
                    try {
                        $current->fill([$field => $value]);
                    } catch (ModelException $error) {
                        $rejected = $error->errorCode() === $code;
                    }
                    exactExpect($rejected, '有损或歧义输入未拒绝：' . $field);
                }
                $connection->raw('DROP TABLE type_model_invoices');
                $connection->raw('CREATE TEMPORARY TABLE type_model_invoices (id ' . $key . ', external_id ' . $large . ', amount '
                    . ($driver === 'sqlite' ? 'NUMERIC' : 'DECIMAL(30,1)') . ', happened_at ' . $date . ', note VARCHAR(255), internal VARCHAR(255))');
                $rejected = false;
                try {
                    (new Invoice(['external_id' => '1', 'amount' => '1.23', 'happened_at' => '2026-09-09T00:00:00Z']))->save();
                } catch (ModelException $error) {
                    $rejected = $error->errorCode() === 'unsafe_exact_storage';
                }
                exactExpect($rejected && (int) $connection->table('type_model_invoices')->aggregate('COUNT') === 0, '不兼容存储没有在写入前拒绝');
                if ($driver !== 'sqlite') {
                    $connection->raw('DROP TABLE type_model_invoices');
                    $connection->raw('CREATE TEMPORARY TABLE type_model_invoices (id ' . $key . ', external_id ' . $large . ', amount '
                        . $amount . ', happened_at ' . ($driver === 'mysql' ? 'DATETIME' : 'TIMESTAMP(0)') . ', note VARCHAR(255), internal VARCHAR(255))');
                    $rejected = false;
                    try {
                        (new Invoice(['external_id' => '1', 'amount' => '1.23', 'happened_at' => '2026-09-09T00:00:00.123456Z']))->save();
                    } catch (ModelException $error) {
                        $rejected = $error->errorCode() === 'unsafe_exact_storage';
                    }
                    exactExpect($rejected && (int) $connection->table('type_model_invoices')->aggregate('COUNT') === 0, '数据库静默截断了微秒');
                }
                echo "精确数值、UTC 微秒、部分字段、可空值与存储兼容检查通过。\n";
            });
        } finally {
            $scope->close();
            $database->close();
        }
    });
}
