<?php

declare(strict_types=1);

use Type\Orm\DatabaseManager;
use Type\Orm\Db;
use Type\Runtime\ExecutionScope;
use TypeApp\ModelExample\Drivers;
use TypeApp\ModelExample\LifecycleExercise;

function main(int $argc, array $argv): void
{
    \Type\Runtime\CoroutineRuntime::run(static function () use ($argv): void {
        $driver = (string) ($argv[1] ?? 'sqlite');
        $database = new DatabaseManager(['default' => Drivers::create($driver)], 1, 0);
        Db::configure($database);
        $scope = new ExecutionScope();
        try {
            $scope->run(static function (ExecutionScope $current) use ($database, &$scope, $argv, $driver): void {
                $connection = Db::connection('default', true);
                $key = $driver === 'mysql' ? 'BIGINT PRIMARY KEY AUTO_INCREMENT'
                    : ($driver === 'pgsql' ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT');
                $date = $driver === 'mysql' ? 'DATETIME(6)' : ($driver === 'pgsql' ? 'TIMESTAMP(6) WITH TIME ZONE' : 'TEXT');
                $connection->raw('CREATE TEMPORARY TABLE type_model_documents (id ' . $key . ', title VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, deleted_at ' . $date . ' NULL, version BIGINT NOT NULL DEFAULT 1)');
                LifecycleExercise::verify($connection);
                echo "软删除、恢复、强制删除、范围搜索、字段转换与事件事务通过。\n";
            });
        } finally {
            $scope->close();
            $database->close();
        }
    });
}
