<?php

declare(strict_types=1);

use Type\Orm\Database;
use Type\Orm\ModelException;
use Type\Runtime\ExecutionScope;
use TypeApp\ModelExample\User;
use TypeApp\ModelExample\Drivers;

function modelExpect(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

function modelRejects(Closure $operation, string $expectedCode): void
{
    try {
        $operation();
    } catch (ModelException $error) {
        modelExpect($error->errorCode() === $expectedCode, '模型错误码不符：' . $error->errorCode());
        return;
    }
    throw new RuntimeException('模型没有拒绝非法操作：' . $expectedCode);
}

function main(int $argc, array $argv): void
{
    $driverName = (string) ($argv[1] ?? 'sqlite');
    $database = new Database(Drivers::create($driverName), 1, 0);
    $scope = new ExecutionScope();
    try {
        $connection = $database->connect($scope);
        $keySql = match ($driverName) {
            'mysql' => 'BIGINT PRIMARY KEY AUTO_INCREMENT',
            'pgsql' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            'sqlite' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
        };
        $connection->raw('CREATE TEMPORARY TABLE type_model_users (id ' . $keySql
            . ', display_name VARCHAR(255) NOT NULL, age INTEGER NOT NULL, active BOOLEAN NOT NULL, secret VARCHAR(255) NOT NULL, note VARCHAR(255) NULL)');
        $user = new User(['name' => '开发者', 'age' => 20, 'active' => true, 'secret' => '私密字段', 'note' => null]);
        modelExpect($user->save($connection) === 'created' && $user->getId() > 0, '模型新增或主键回填失败');
        $id = $user->getId();
        $loaded = User::query($connection)->find($id);
        modelExpect($loaded instanceof User && $loaded->getName() === '开发者' && $loaded->getActive() && $loaded->getNote() === null, '类型化水合失败');
        modelExpect(!array_key_exists('secret', $loaded->toArray()), '模型输出包含隐藏字段');
        modelExpect(!array_key_exists('secret', json_decode(json_encode($loaded, JSON_THROW_ON_ERROR), true)), 'JSON 输出包含隐藏字段');
        modelRejects(static fn () => $loaded->project(['secret']), 'hidden_field');
        modelExpect($loaded->save($connection) === 'unchanged' && $loaded->dirty() === [], '未修改模型不应写入');
        $partial = User::query($connection)->select(['name'])->find($id);
        modelExpect($partial instanceof User && !$partial->loaded('age'), '部分字段被伪装成已加载');
        modelRejects(static fn () => $partial->getAge(), 'field_not_loaded');
        $partial->setName('已修改');
        modelExpect($partial->save($connection) === 'updated', '部分更新没有持久化');
        $fresh = User::query($connection)->find($id);
        modelExpect($fresh->getName() === '已修改' && $fresh->getAge() === 20 && $fresh->getSecret() === '私密字段', '部分更新覆盖了未加载字段');
        modelRejects(static fn () => $fresh->fill(['name' => '错误修改', 'unknown' => 1]), 'unknown_field');
        modelExpect($fresh->getName() === '已修改', '失败批量赋值产生部分修改');
        modelRejects(static fn () => $fresh->fill(['id' => 99]), 'field_not_fillable');
        modelRejects(static fn () => (new User(['name' => '缺少字段']))->save($connection), 'required_field');
        $fresh->setNote('已提供');
        $fresh->save($connection);
        $fresh->setNote(null);
        modelExpect($fresh->dirty() === ['note' => null], 'null 更新未被追踪');
        $fresh->save($connection);
        modelExpect(User::query($connection)->find($id)->getNote() === null, 'null 没有持久化');
        $base = User::query($connection);
        modelExpect($base->where('age', '=', 99)->get() === [] && $base->count() === 1, '模型共享查询被修改');
        modelExpect($base->find(99999) === null && $base->where('age', '=', 99)->first() === null, '未找到语义不一致');
        modelExpect($fresh->delete($connection) && User::query($connection)->find($id) === null, '模型删除失败');
        modelRejects(static fn () => $fresh->getName(), 'model_invalid');
        modelRejects(static fn () => $fresh->toArray(), 'model_invalid');
        modelRejects(static fn () => json_encode($fresh, JSON_THROW_ON_ERROR), 'model_invalid');
        modelRejects(static fn () => serialize($fresh), 'model_invalid');
        echo "模型 CRUD、生成水合、部分字段、安全输出与状态检查通过。\n";
    } finally {
        $scope->close();
        $database->close();
    }
}
