<?php

declare(strict_types=1);

use Type\Orm\DatabaseManager;
use Type\Orm\Db;
use Type\Orm\ModelException;
use Type\Runtime\ExecutionScope;
use TypeApp\ModelExample\User;
use TypeApp\ModelExample\Drivers;
use TypeApp\ModelExample\ScopedRecord;
use TypeApp\ModelExample\ScopedLabel;

function modelExpect(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

function modelRejects(Closure $operation, string $expectedCode): void
{
    try {
        $operation();
    } catch (ModelException $error) {
        modelExpect($error->errorCode() === $expectedCode, '模型错误码不符：' . $error->errorCode());
        return;
    }
    throw new RuntimeException('模型没有拒绝非法操作：' . $expectedCode);
}

function main(int $argc, array $argv): void
{
    \Type\Runtime\CoroutineRuntime::run(static function () use ($argv): void {
        $driverName = (string) ($argv[1] ?? 'sqlite');
        $database = new DatabaseManager(['default' => Drivers::create($driverName), 'archive' => Drivers::create($driverName)], 1, 0);
        Db::configure($database);
        $scope = new ExecutionScope();
        try {
            $scope->run(static function (ExecutionScope $current) use ($database, $driverName): void {
                $lazy = User::query()->where('active', '=', true);
                modelExpect($database->statistics()['active'] === [], '构造模型查询提前借用了连接');
                $connection = Db::connection('default', true);
                $keySql = match ($driverName) {
                    'mysql' => 'BIGINT PRIMARY KEY AUTO_INCREMENT',
                    'pgsql' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
                    'sqlite' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
                };
                $connection->raw('CREATE TEMPORARY TABLE type_model_users (id ' . $keySql
                    . ', display_name VARCHAR(255) NOT NULL, age INTEGER NOT NULL, active BOOLEAN NOT NULL, secret VARCHAR(255) NOT NULL, note VARCHAR(255) NULL)');
                $user = new User(['name' => '开发者', 'age' => 20, 'active' => true, 'secret' => '私密字段', 'note' => null]);
                modelExpect($user->save() === 'created' && $user->getId() > 0, '模型新增或主键回填失败');
                $id = $user->getId();
                $loaded = User::query()->find($id);
                modelExpect($loaded instanceof User && $loaded->getName() === '开发者' && $loaded->getActive() && $loaded->getNote() === null, '类型化水合失败');
                modelExpect(!array_key_exists('secret', $loaded->toArray()), '模型输出包含隐藏字段');
                modelExpect(!array_key_exists('secret', json_decode(json_encode($loaded, JSON_THROW_ON_ERROR), true)), 'JSON 输出包含隐藏字段');
                modelRejects(static fn () => $loaded->project(['secret']), 'hidden_field');
                modelExpect($loaded->save() === 'unchanged' && $loaded->dirty() === [], '未修改模型不应写入');
                $partial = User::query()->select(['name'])->find($id);
                modelExpect($partial instanceof User && !$partial->loaded('age'), '部分字段被伪装成已加载');
                modelRejects(static fn () => $partial->getAge(), 'field_not_loaded');
                $partial->setName('已修改');
                modelExpect($partial->save() === 'updated', '部分更新没有持久化');
                $fresh = User::query()->find($id);
                modelExpect($fresh->getName() === '已修改' && $fresh->getAge() === 20 && $fresh->getSecret() === '私密字段', '部分更新覆盖了未加载字段');
                modelRejects(static fn () => $fresh->fill(['name' => '错误修改', 'unknown' => 1]), 'unknown_field');
                modelExpect($fresh->getName() === '已修改', '失败批量赋值产生部分修改');
                modelRejects(static fn () => $fresh->fill(['id' => 99]), 'field_not_fillable');
                modelRejects(static fn () => (new User(['name' => '缺少字段']))->save(), 'required_field');
                $fresh->setNote('已提供');
                $fresh->save();
                $fresh->setNote(null);
                modelExpect($fresh->dirty() === ['note' => null], 'null 更新未被追踪');
                $fresh->save();
                modelExpect(User::query()->find($id)->getNote() === null, 'null 没有持久化');
                $base = User::query();
                modelExpect($base->where('age', '=', 99)->get() === [] && $base->count() === 1, '模型共享查询被修改');
                modelExpect($base->find(99999) === null && $base->where('age', '=', 99)->first() === null, '未找到语义不一致');
                modelExpect($fresh->delete() && User::query()->find($id) === null, '模型删除失败');
                modelRejects(static fn () => $fresh->getName(), 'model_invalid');
                modelRejects(static fn () => $fresh->toArray(), 'model_invalid');
                modelRejects(static fn () => json_encode($fresh, JSON_THROW_ON_ERROR), 'model_invalid');
                modelRejects(static fn () => serialize($fresh), 'model_invalid');
                $helper = User::search(['active' => true, 'keyword' => '已修改'])->equal('active')->like(['keyword' => 'name']);
                modelExpect($helper instanceof \Type\Orm\Helper\QueryHelper, '静态 search 没有返回查询助手');
                $pending = User::query()->master();
                $committed = [];
                $result = Db::transaction(static function () use ($pending, &$committed): string {
                    modelExpect($pending->count() === 0, '事务前构造的查询没有沿用事务连接');
                    modelRejects(static fn () => Db::connection('archive'), 'cross_database_transaction');
                    Db::afterCommit(static function () use (&$committed): void {
                        $committed[] = 'committed';
                    });
                    return 'result';
                });
                modelExpect($result === 'result' && $committed === ['committed'], '事务结果或提交后回调错误');
                $innerScope = new ExecutionScope();
                try {
                    $innerScope->run(static function (ExecutionScope $current) use ($pending): void {
                        modelRejects(static fn () => $pending->count(), 'model_scope_mismatch');
                    });
                } finally {
                    $innerScope->close();
                }
                modelTenantChecks($current, $keySql, $driverName);
                echo "模型 CRUD、生成水合、部分字段、安全输出与状态检查通过。\n";
            });
        } finally {
            $scope->close();
            $database->close();
        }
    });
}

/** 同一公开入口验证自动范围、原始归属和生命周期，不依赖应用身份表。 */
function modelTenantChecks(ExecutionScope $scope, string $keySql, string $driver): void
{
    $connection = Db::connection('default', true);
    $dateSql = match ($driver) {
        'mysql' => 'DATETIME(6)', 'pgsql' => 'TIMESTAMP(6)', default => 'TEXT'
    };
    $connection->raw('CREATE TEMPORARY TABLE type_model_scoped_records (id ' . $keySql
        . ', tenant_id VARCHAR(50) NOT NULL, user_id INTEGER NOT NULL, title VARCHAR(100) NOT NULL, value INTEGER NOT NULL, deleted_at '
        . $dateSql . ' NULL, version BIGINT NOT NULL)');
    $connection->raw('CREATE TEMPORARY TABLE type_model_scoped_labels (id ' . $keySql
        . ', owner_ref VARCHAR(50) NOT NULL, scope_id VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL)');
    $connection->raw('CREATE TEMPORARY TABLE type_model_scoped_links (user_id INTEGER NOT NULL, label_id INTEGER NOT NULL, tenant_id VARCHAR(50) NOT NULL, PRIMARY KEY (user_id, label_id, tenant_id))');
    modelRejects(static fn () => ScopedRecord::query()->count(), 'tenant_scope_required');
    modelRejects(static fn () => new ScopedRecord(['user_id' => 1, 'title' => '无身份', 'value' => 0]), 'tenant_scope_required');
    $untrusted = new ExecutionScope(context: ['tenant_id' => 'tenant-a']);
    try {
        $untrusted->run(static function (ExecutionScope $current): void {
            modelRejects(static fn () => ScopedRecord::query()->count(), 'tenant_scope_required');
        });
    } finally {
        $untrusted->close();
    }
    $user = new User(['name' => '全局账号', 'age' => 20, 'active' => true, 'secret' => '内部', 'note' => null]);
    $user->save();
    $userId = $user->getId();
    $ids = [];
    $labels = [];
    foreach (['tenant-a', 'tenant-b'] as $tenant) {
        $ids[$tenant] = $scope->run(static function (ExecutionScope $current) use ($userId, $tenant, &$labels): int {
            $record = new ScopedRecord(['user_id' => $userId, 'title' => $tenant, 'value' => 1]);
            modelExpect($record->getTenantId() === $tenant && $record->save() === 'created', '租户新增没有自动填充');
            $label = new ScopedLabel(['scope_id' => '普通业务值', 'label' => $tenant]);
            $label->save();
            $labels[$tenant] = $label->getId();
            $parent = User::query()->find($userId);
            $links = $parent->definition()->relation('labels')->loader();
            modelExpect($links->attach($parent, $label->getId()), '带租户中间表未自动填充归属');
            modelExpect($label->getWorkspace() === $tenant, '自定义租户属性没有填充');
            return $record->getId();
        }, ['tenant_id' => $tenant]);
    }
    modelRejects(static fn () => User::query()->with('labels')->find($userId), 'tenant_scope_required');
    $scope->run(static function (ExecutionScope $current) use ($userId, $labels): void {
        $parent = User::query()->with('labels')->withCount('labels')->find($userId);
        modelExpect(count($parent->related('labels')) === 1 && $parent->related('labels')[0]->getId() === $labels['tenant-a']
            && $parent->computed('labels_count') === 1, '中间表预加载或聚合泄漏租户');
        $links = $parent->definition()->relation('labels')->loader();
        modelRejects(static fn () => $links->attach($parent, $labels['tenant-b']), 'related_not_found');
        $parent = User::query()->find($userId);
        modelRejects(static fn () => $links->attach($parent, $labels['tenant-a'], ['tenant_id' => 'tenant-b']), 'invalid_pivot_field');
        modelExpect(!$links->detach($parent, $labels['tenant-b']), '解绑影响其他租户关系');
        // 无租户列的绑定同样受目标模型范围约束；不能整组删除不可见目标。
        $unscoped = \Type\Orm\Relation::belongsToMany(
            static fn (\Type\Orm\Connection $connection): \Type\Orm\ModelQuery => ScopedLabel::query()->onConnection($connection),
            'type_model_scoped_links',
            'user_id',
            'label_id'
        );
        modelExpect($unscoped->sync($parent, []) === ['attached' => 0, 'detached' => 1, 'updated' => 0], '全局父模型同步删除越出租户目标范围');
        modelExpect($links->attach($parent, $labels['tenant-a']) && $links->sync($parent, [])['detached'] === 1, '租户中间表同步失败');
        modelExpect(!User::query()->whereHas('labels')->where('id', '=', $userId)->exists(), '关联筛选泄漏其他租户绑定');
        // 受控底层写入模拟不一致绑定，验证中间表范围不能仅依靠目标模型。
        Db::connection('default', true)->table('type_model_scoped_links')->insert(['user_id' => $userId, 'label_id' => $labels['tenant-a'], 'tenant_id' => 'tenant-b']);
        $view = User::query()->with('labels')->withCount('labels')->find($userId);
        modelExpect($view->related('labels') === [] && $view->computed('labels_count') === 0, '中间表自身范围未覆盖预加载和关联子查询');
        modelExpect(!$links->detach($parent, $labels['tenant-a']) && $links->sync($parent, [])['detached'] === 0, '中间表写入越过自身租户范围');
    }, ['tenant_id' => 'tenant-a']);
    $scope->run(static function (ExecutionScope $current) use ($userId, $labels): void {
        $view = User::query()->with('labels')->find($userId);
        modelExpect(count($view->related('labels')) === 1 && $view->related('labels')[0]->getId() === $labels['tenant-b'], '其他租户关联被破坏');
    }, ['tenant_id' => 'tenant-b']);
    $scope->run(static function (ExecutionScope $current) use ($ids, $userId): void {
        $base = ScopedRecord::query();
        $list = ScopedRecord::search(['title' => 'tenant-a'])->equal('title')->query()->get();
        modelExpect(count($list) === 1 && $list[0] instanceof ScopedRecord && $list[0]->getId() === $ids['tenant-a'], 'search 范围或水合不正确');
        modelExpect($base->where('title', '=', '不存在')->orWhere('title', '=', 'tenant-b')->count() === 0, 'OR 放宽了租户范围');
        modelExpect($base->count() === 1 && $base->find($ids['tenant-b']) === null && count($base->paginate(1, 10)->items()) === 1, '查询或分页泄露其他租户');
        modelExpect(ScopedLabel::query()->count() === 1 && ScopedLabel::query()->first()->getScopeId() === '普通业务值', '自定义字段范围错误');
        $related = \Type\Orm\Relation::hasMany(static fn (\Type\Orm\Connection $connection): \Type\Orm\ModelQuery => ScopedRecord::query()->onConnection($connection), 'user_id');
        $global = User::query()->with('records', $related)->find($userId);
        modelExpect(count($global->related('records')) === 1 && $global->related('records')[0]->getTenantId() === 'tenant-a', '全局模型关系没有隔离目标租户');
        $partial = $base->select(['title'])->find($ids['tenant-a']);
        modelExpect(!$partial->loaded('tenant_id'), '部分投影伪装加载租户字段');
        $partial->setTitle('部分更新');
        modelExpect($partial->save() === 'updated' && $partial->getVersion() === 2, '部分投影丢失持久化归属或版本');
        modelRejects(static fn () => $partial->setTenantId('tenant-b'), 'tenant_scope_conflict');
        modelRejects(static fn () => $partial->fill(['title' => '错误', 'tenant_id' => 'tenant-b']), 'tenant_scope_conflict');
        modelExpect($partial->getTitle() === '部分更新', '失败赋值产生部分修改');
        modelRejects(static fn () => new ScopedRecord(['tenant_id' => 'tenant-b']), 'tenant_scope_conflict');
        modelRejects(static fn () => $base->increment('tenant_id'), 'invalid_increment_field');
        $current->run(static function (ExecutionScope $inner) use ($base, $partial): void {
            modelRejects(static fn () => $base->count(), 'tenant_context_changed');
            modelRejects(static fn () => $partial->save(), 'tenant_context_changed');
            modelExpect(ScopedRecord::query()->count() === 1, '新租户查询没有独立范围');
        }, ['tenant_id' => 'tenant-b']);
        modelExpect($base->count() === 1 && $partial->getTitle() === '部分更新', '返回外层没有恢复可信上下文');
        modelExpect($partial->delete() && $base->count() === 0 && $base->onlyTrashed()->count() === 1 && $base->withTrashed()->count() === 1, '软删除改变租户隔离');
        modelExpect($partial->restore() && $partial->touch() === 'updated' && $partial->forceDelete() && $base->withTrashed()->count() === 0, '恢复或强制删除丢失租户归属');
    }, ['tenant_id' => 'tenant-a']);
    $scope->run(static function (ExecutionScope $current): void {
        modelExpect(ScopedRecord::query()->count() === 1 && ScopedRecord::query()->first()->getVersion() === 1, '其他租户记录被修改');
    }, ['tenant_id' => 'tenant-b']);
    modelExpect($scope->binding('tenant_id') === null, '完成后遗留租户上下文');
}
