<?php

declare(strict_types=1);

use Type\Orm\Connection;
use Type\Orm\Database;
use Type\Orm\Pgsql\PgsqlDriver;
use Type\Runtime\ExecutionScope;

function databaseExpect(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

/** 在专用测试库建立真实角色和schema，关闭角色连接后回收，验证状态不会污染原会话。 */
function databaseSession(Connection $owner): void
{
    $name = 'type_session_' . bin2hex(random_bytes(6));
    $createdSchema = false;
    $sessionScope = new ExecutionScope();
    $sessionDatabase = new Database(new PgsqlDriver(
        (string) (getenv('TYPE_PGSQL_HOST') ?: '127.0.0.1'),
        (int) (getenv('TYPE_PGSQL_PORT') ?: '5432'),
        (string) (getenv('TYPE_PGSQL_DATABASE') ?: 'type_app_test'),
        (string) (getenv('TYPE_PGSQL_USER') ?: 'type_app'),
        (string) (getenv('TYPE_PGSQL_PASSWORD') ?: ''),
        schema: $name,
        databaseRole: $name
    ), 1, 0);
    $owner->raw('CREATE ROLE ' . $name);
    try {
        $owner->raw('CREATE SCHEMA ' . $name . ' AUTHORIZATION ' . $name);
        $createdSchema = true;
        $selected = $sessionDatabase->connect($sessionScope);
        $actual = $selected->query('SELECT current_user AS role, current_schema() AS schema')[0];
        databaseExpect($actual['role'] === $name && $actual['schema'] === $name, 'PostgreSQL 没有应用选定角色和schema');
        $selected->raw('CREATE TABLE session_probe (value INTEGER NOT NULL)');
        $selected->execute('INSERT INTO session_probe VALUES (?)', [7]);
        databaseExpect((int) $selected->query('SELECT value FROM session_probe')[0]['value'] === 7, '角色没有在选定schema中完成真实读写');
        $original = $owner->query('SELECT current_user AS role, current_schema() AS schema')[0];
        databaseExpect($original['role'] !== $name && $original['schema'] !== $name, 'PostgreSQL 角色状态污染了其他连接');
    } finally {
        try {
            $sessionScope->close();
            $sessionDatabase->close();
        } finally {
            if ($createdSchema) {
                $owner->raw('DROP SCHEMA ' . $name . ' CASCADE');
            }
            $owner->raw('DROP ROLE ' . $name);
        }
    }
}

function main(int $argc, array $argv): void
{
    if (($argv[1] ?? '') === 'test-drivers') {
        echo json_encode(PDO::getAvailableDrivers(), JSON_THROW_ON_ERROR) . "\n";
        return;
    }
    $scope = new ExecutionScope();
    $database = new Database(new PgsqlDriver(
        (string) (getenv('TYPE_PGSQL_HOST') ?: '127.0.0.1'),
        (int) (getenv('TYPE_PGSQL_PORT') ?: '5432'),
        (string) (getenv('TYPE_PGSQL_DATABASE') ?: 'type_app_test'),
        (string) (getenv('TYPE_PGSQL_USER') ?: 'type_app'),
        (string) (getenv('TYPE_PGSQL_PASSWORD') ?: '')
    ), 1, 1);
    try {
        $connection = $database->connect($scope);
        $session = $connection->query("SELECT current_setting('TimeZone') AS zone, current_setting('DateStyle') AS style")[0];
        databaseExpect($session['zone'] === 'UTC' && $session['style'] === 'ISO, YMD', 'PostgreSQL 会话基线未应用');
        databaseSession($connection);
        $connection->raw('CREATE TEMPORARY TABLE type_app_probe (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL)');
        $inserted = $connection->query('INSERT INTO type_app_probe (name) VALUES (?) RETURNING id', ["原生数据' OR 1=1 --"]);
        $id = (string) $inserted[0]['id'];
        databaseExpect($id === '1', 'PostgreSQL 主键返回不正确');
        databaseExpect($connection->query('SELECT name FROM type_app_probe WHERE id = ?', [$id])[0]['name'] === "原生数据' OR 1=1 --", '参数未作为数据绑定');
        $connection->execute('UPDATE type_app_probe SET name = ? WHERE id = ?', ['已更新', $id]);
        databaseExpect($connection->query('SELECT name FROM type_app_probe WHERE id = ?', [$id])[0]['name'] === '已更新', '读取或更新失败');
        $rolledBack = false;
        try {
            $connection->transaction(static function (Connection $transaction): void {
                $transaction->execute('INSERT INTO type_app_probe (name) VALUES (?)', ['应回滚']);
                throw new RuntimeException('主动回滚');
            });
        } catch (RuntimeException $error) {
            $rolledBack = $error->getMessage() === '主动回滚';
        }
        databaseExpect($rolledBack && count($connection->query('SELECT * FROM type_app_probe')) === 1, 'PostgreSQL 回滚失败');
        $connection->transaction(static function (Connection $transaction): void {
            $transaction->execute('INSERT INTO type_app_probe (name) VALUES (?)', ['已提交']);
        });
        databaseExpect(count($connection->query('SELECT * FROM type_app_probe')) === 2, 'PostgreSQL 提交失败');
        $full = false;
        try {
            $database->connect($scope, 0);
        } catch (\Type\Runtime\CapacityException $error) {
            $full = true;
        }
        databaseExpect($full, '连接池容量未生效');
        $connection->execute('DELETE FROM type_app_probe WHERE id = ?', [$id]);
        databaseExpect(count($connection->query('SELECT * FROM type_app_probe')) === 1, '删除失败');
        $errorCaught = false;
        try {
            $connection->query('SELECT nonexistent_column FROM type_app_probe');
        } catch (\Type\Orm\DatabaseException $error) {
            $errorCaught = str_contains($error->getMessage(), 'SQLSTATE') && !str_contains($error->getMessage(), 'nonexistent_column');
        }
        databaseExpect($errorCaught, 'SQL 错误未分类');
        $connection->close();
        $next = $database->connect($scope);
        databaseExpect((int) $next->query('SELECT 7 AS value')[0]['value'] === 7, '归还后不能重新借用');
        $scope->close();
        $closed = false;
        try {
            $next->query('SELECT 1');
        } catch (RuntimeException $error) {
            $closed = true;
        }
        databaseExpect($closed, '关闭作用域后仍可查询');
        echo "PostgreSQL 原生读写、事务与连接池验证通过。\n";
    } catch (Throwable $error) {
        fwrite(STDERR, '数据库命令失败：' . $error->getMessage() . PHP_EOL);
        $scope->close();
        $database->close();
        exit(70);
    }
    $scope->close();
    $database->close();
}
