<?php

declare(strict_types=1);

use Type\Orm\Connection;
use Type\Orm\DatabaseManager;
use Type\Orm\Db;
use Type\Orm\ModelException;
use Type\Runtime\ExecutionScope;
use TypeApp\ModelExample\Article;
use TypeApp\ModelExample\ArticleTags;
use TypeApp\ModelExample\Drivers;

/**
 * 将当前示例的行为断言转为明确失败，避免只输出成功文字而忽略实际状态。
 *
 * @throws \RuntimeException 条件不成立。
 */
function pivotExpect(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

/**
 * 验证多对多挂载、同步、事务与中间表字段；竞争阶段由参数显式选择。
 *
 * @param list<string> $argv 程序路径与该示例的显式参数。
 */
function main(int $argc, array $argv): void
{
    \Type\Runtime\CoroutineRuntime::run(static function () use ($argv): void {
        $driver = (string) ($argv[1] ?? 'sqlite');
        $database = new DatabaseManager(['default' => Drivers::create($driver)], 1, 0);
        Db::configure($database);
        $scope = new ExecutionScope();
        try {
            $scope->run(static function (ExecutionScope $current) use ($database, &$scope, $argv, $driver): void {
                $connection = Db::connection('default', true);
                if (($argv[2] ?? '') === 'race') {
                    $parent = Article::query()->find(10);
                    $barrier = (string) getenv('TYPE_PIVOT_BARRIER');
                    if ($barrier === '') {
                        throw new RuntimeException('并发验证缺少同步文件');
                    }
                    file_put_contents($barrier, "ready\n", FILE_APPEND | LOCK_EX);
                    $deadline = microtime(true) + 5;
                    while (substr_count((string) file_get_contents($barrier), "\n") < 2) {
                        if (microtime(true) >= $deadline) {
                            throw new RuntimeException('并发验证等待超时');
                        }
                        usleep(1000);
                    }
                    echo ArticleTags::relation()->attach($parent, 100) ? "attached\n" : "existing\n";
                    return;
                }
                // 验证器为本程序创建独立数据库；三个表都具有真实键约束。
                $key = $driver === 'mysql' ? 'BIGINT PRIMARY KEY AUTO_INCREMENT'
                    : ($driver === 'pgsql' ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT');
                $engine = $driver === 'mysql' ? ' ENGINE=InnoDB' : '';
                $connection->raw('CREATE TABLE type_model_articles (id ' . $key . ', user_id BIGINT NULL, title VARCHAR(255) NOT NULL)' . $engine);
                $connection->raw('CREATE TABLE type_model_tags (id ' . $key . ', label VARCHAR(255) NOT NULL, internal VARCHAR(255) NOT NULL)' . $engine);
                $connection->raw('CREATE TABLE type_model_article_tag (article_id BIGINT NOT NULL, tag_id BIGINT NOT NULL, position INTEGER NOT NULL DEFAULT 0, '
                    . 'PRIMARY KEY (article_id, tag_id), FOREIGN KEY (article_id) REFERENCES type_model_articles(id) ON DELETE CASCADE, '
                    . 'FOREIGN KEY (tag_id) REFERENCES type_model_tags(id) ON DELETE CASCADE)' . $engine);
                $connection->table('type_model_articles')->insertMany([['id' => 10, 'user_id' => null, 'title' => '文章甲'], ['id' => 11, 'user_id' => null, 'title' => '文章乙']]);
                $connection->table('type_model_tags')->insertMany([
                    ['id' => 100, 'label' => 'PHP', 'internal' => '私有'], ['id' => 101, 'label' => '框架', 'internal' => '私有'],
                    ['id' => 102, 'label' => '编译', 'internal' => '私有'],
                ]);
                $a = Article::query()->find(10);
                $b = Article::query()->find(11);
                $tags = ArticleTags::relation(2);
                pivotExpect($tags->attach($a, 100, ['position' => 1]), '首次挂载没有新增关系');
                pivotExpect(!$tags->attach($a, 100, ['position' => 2]), '重复挂载产生新关系');
                $tags->attach($a, 101, ['position' => 3]);
                $tags->attach($b, 100, ['position' => 9]);
                $tags->attach($b, 102, ['position' => 4]);
                $before = $connection->statistics()['read_attempts'];
                $posts = Article::query()->select(['title'])->with('tags', $tags)->orderBy('id')->get();
                pivotExpect($connection->statistics()['read_attempts'] - $before === 4, '多对多预加载出现逐记录查询');
                pivotExpect(array_slice($connection->statistics()['recent_read_parameter_sizes'], -4) === [0, 2, 2, 1], '中间表或目标查询批量不符');
                pivotExpect($posts[0]->related('tags')[0]->pivot() === ['position' => 2]
                    && $posts[1]->related('tags')[0]->pivot() === ['position' => 9], '同一标签的不同中间表状态相互污染');
                pivotExpect($posts[0]->project(['title'], ['tags' => ['label']]) === ['title' => '文章甲', 'tags' => [['label' => 'PHP'], ['label' => '框架']]], '多对多输出字段或顺序错误');
                pivotExpect(!$tags->detach($posts[0], 999) && !$posts[0]->relationLoaded('tags'), '解除不存在关系或旧预加载状态错误');
                $result = $tags->sync($a, [['id' => 101, 'pivot' => ['position' => 8]], ['id' => 102, 'pivot' => ['position' => 7]]]);
                pivotExpect($result === ['attached' => 1, 'detached' => 1, 'updated' => 1], '同步结果错误');
                $rejected = false;
                try {
                    $tags->sync($a, [['id' => 999]]);
                } catch (ModelException $error) {
                    $rejected = $error->errorCode() === 'related_not_found';
                }
                pivotExpect($rejected, '同步不存在的目标未拒绝');
                $a = Article::query()->with('tags', $tags)->find(10);
                pivotExpect(count($a->related('tags')) === 2 && $a->related('tags')[0]->getId() === 101, '失败同步改变了已有关系');
                $result = $tags->sync($a, []);
                pivotExpect($result === ['attached' => 0, 'detached' => 2, 'updated' => 0], '同步空集合没有只移除当前父记录的关系');
                pivotExpect(count(Article::query()->with('tags', $tags)->find(11)->related('tags')) === 2, '同步误删了其他文章关系');
                try {
                    $connection->transaction(static function (Connection $transaction) use ($tags, $b): void {
                        $tags->attach($b, 101, ['position' => 6]);
                        throw new RuntimeException('回滚关系');
                    });
                } catch (RuntimeException $error) {
                    pivotExpect($error->getMessage() === '回滚关系', '关系事务异常不符');
                }
                $b = Article::query()->with('tags', $tags)->find(11);
                pivotExpect(count($b->related('tags')) === 2, '关系写入没有随外层事务回滚');
                $rejected = false;
                try {
                    $connection->table('type_model_article_tag')->insert(['article_id' => 11, 'tag_id' => 100, 'position' => 0]);
                } catch (\Type\Orm\DatabaseException) {
                    $rejected = true;
                }
                pivotExpect($rejected, '数据库没有真实唯一关系约束');
                echo "多对多挂载、解除、同步、事务、中间表字段与批量读取通过。\n";
            });
        } finally {
            $scope->close();
            $database->close();
        }
    });
}
