<?php

declare(strict_types=1);

use Type\Orm\Connection;
use Type\Orm\DatabaseManager;
use Type\Orm\Db;
use Type\Runtime\ExecutionScope;
use TypeApp\ModelExample\Drivers;
use TypeApp\ModelExample\TransactionExercise;

function main(int $argc, array $argv): void
{
    \Type\Runtime\CoroutineRuntime::run(static function () use ($argv): void {
        $name = (string) ($argv[1] ?? 'sqlite');
        $database = new DatabaseManager(['default' => Drivers::create($name)], 1, 0);
        Db::configure($database);
        $scope = new ExecutionScope();
        try {
            $scope->run(static function (ExecutionScope $current) use ($database, &$scope, $argv, $name): void {
                $connection = Db::connection('default', true);
                $key = match ($name) {
                    'mysql' => 'BIGINT PRIMARY KEY AUTO_INCREMENT',
                    'pgsql' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
                    'sqlite' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
                };
                $connection->raw('CREATE TEMPORARY TABLE type_model_users (id ' . $key
                    . ', display_name VARCHAR(255) NOT NULL, age INTEGER NOT NULL, active BOOLEAN NOT NULL, secret VARCHAR(255) NOT NULL, note VARCHAR(255) NULL)');
                TransactionExercise::verify($connection);
                $ownerRejected = false;
                $connection->transaction(static function (Connection $transaction) use (&$ownerRejected): void {
                    $fiber = new Fiber(static function () use ($transaction, &$ownerRejected): void {
                        try {
                            $transaction->query('SELECT 1');
                        } catch (RuntimeException $error) {
                            $ownerRejected = str_contains($error->getMessage(), '执行者');
                        }
                    });
                    $fiber->start();
                });
                if (!$ownerRejected) {
                    throw new RuntimeException('事务连接被其他执行者使用');
                }
                $scopeRejected = false;
                $fiber = new Fiber(static function () use ($scope, &$scopeRejected): void {
                    try {
                        $scope->close();
                    } catch (RuntimeException $error) {
                        $scopeRejected = str_contains($error->getMessage(), '执行者');
                    }
                });
                $fiber->start();
                if (!$scopeRejected) {
                    throw new RuntimeException('其他执行者关闭了当前作用域');
                }
                if ($name === 'sqlite') {
                    $connection->transaction(static fn (Connection $transaction): array => $transaction->query('SELECT 1'), 'immediate');
                }
                $held = false;
                $cancelled = false;
                try {
                    $connection->transaction(static function (Connection $transaction) use ($database, &$held): void {
                        $transaction->close();
                        $peer = new ExecutionScope();
                        try {
                            $database->connect($peer, 'default', 0);
                        } catch (\Type\Runtime\CapacityException $error) {
                            $held = true;
                        } finally {
                            $peer->close();
                        }
                    });
                } catch (RuntimeException $error) {
                    $cancelled = str_contains($error->getMessage(), '租约已经归还');
                }
                if (!$held || !$cancelled || $database->statistics()['active']['default']['created'] !== 0 || $connection->transactionDepth() !== 0) {
                    throw new RuntimeException('关闭事务租约时过早归池或没有安全收尾');
                }
                echo "嵌套事务、回滚模型失效、执行者隔离与活动租约收尾通过。\n";
            });
        } finally {
            $scope->close();
            $database->close();
        }
    });
}
