<?php

declare(strict_types=1);

namespace app\common\database;

use InvalidArgumentException;
use Type\Orm\Migration\Migration;

/** 用户示例的版本化表结构；数据库差异明确记录在迁移声明中。 */
final class Schema
{
    /**
     * 只返回声明，不连接数据库；MySQL 的非事务 DDL 不能承诺自动回滚。
     *
     * @return list<Migration>
     * @throws InvalidArgumentException 驱动不属于该应用的支持范围。
     */
    public static function migrations(string $driver): array
    {
        if (!in_array($driver, ['mysql', 'pgsql', 'sqlite'], true)) {
            throw new InvalidArgumentException('迁移不支持所选数据库驱动');
        }
        $id = $driver === 'mysql' ? 'INTEGER PRIMARY KEY AUTO_INCREMENT'
            : ($driver === 'pgsql' ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT');
        $date = $driver === 'mysql' ? 'DATETIME(6)' : ($driver === 'pgsql' ? 'TIMESTAMP(6) WITHOUT TIME ZONE' : 'TEXT');

        return [new Migration('001_users', '创建用户、乐观锁与软删除字段', [
            'CREATE TABLE users (id ' . $id . ', name VARCHAR(100) NOT NULL, age INTEGER NOT NULL, email VARCHAR(255) NULL, '
                . 'version INTEGER NOT NULL DEFAULT 1, deleted_at ' . $date . ' NULL)' . ($driver === 'mysql' ? ' ENGINE=InnoDB' : ''),
        ], $driver !== 'mysql')];
    }
}
