<?php

declare(strict_types=1);

namespace TypeApp\OrmSuite;

use Type\Orm\Migration\Migration;

/** 三种物理存储声明明确列出差异；业务层始终使用同一模型与操作。 */
final class Schema
{
    /**
     * 为同一业务声明三库等价表与约束，保留主键和字段存储的真实差异。
     *
     * @return list<\Type\Orm\Migration\Migration>
     */
    public static function plan(string $driver): array
    {
        $id = match ($driver) {
            'mysql' => 'INTEGER AUTO_INCREMENT PRIMARY KEY',
            'pgsql' => 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            'sqlite' => 'INTEGER PRIMARY KEY',
            default => throw new \InvalidArgumentException('未知三库业务驱动'),
        };
        $number = $driver === 'sqlite' ? 'TEXT' : 'DECIMAL(30, 0)';
        $money = $driver === 'sqlite' ? 'TEXT' : 'DECIMAL(30, 2)';
        $date = match ($driver) {
            'mysql' => 'DATETIME(6)', 'pgsql' => 'TIMESTAMP(6) WITHOUT TIME ZONE', default => 'TEXT'
        };
        $json = match ($driver) {
            'mysql' => 'JSON', 'pgsql' => 'JSONB', default => 'TEXT'
        };
        $suffix = $driver === 'mysql' ? ' ENGINE=InnoDB' : '';
        return [new Migration('202609090001', '建立用户、文章、标签与关系表', [
            'CREATE TABLE type_suite_users (id ' . $id . ', display_name VARCHAR(100) NOT NULL, active BOOLEAN NOT NULL, external_id ' . $number . ' NOT NULL, credit ' . $money . ' NOT NULL, profile ' . $json . ' NOT NULL, joined_at ' . $date . ' NOT NULL, secret VARCHAR(255) NOT NULL)' . $suffix,
            'CREATE TABLE type_suite_articles (id ' . $id . ', user_id INTEGER NOT NULL, title VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL, views INTEGER NOT NULL, deleted_at ' . $date . ' NULL, version BIGINT NOT NULL, FOREIGN KEY (user_id) REFERENCES type_suite_users(id))' . $suffix,
            'CREATE TABLE type_suite_tags (id ' . $id . ', label VARCHAR(50) NOT NULL UNIQUE)' . $suffix,
            'CREATE TABLE type_suite_details (id ' . $id . ', user_id INTEGER NOT NULL UNIQUE, bio VARCHAR(255) NOT NULL, FOREIGN KEY (user_id) REFERENCES type_suite_users(id))' . $suffix,
            'CREATE TABLE type_suite_article_tags (article_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, weight INTEGER NOT NULL, PRIMARY KEY (article_id, tag_id), FOREIGN KEY (article_id) REFERENCES type_suite_articles(id), FOREIGN KEY (tag_id) REFERENCES type_suite_tags(id))' . $suffix,
        ], $driver !== 'mysql'), new Migration('202609090002', '增加文章列表查询索引', [
            'CREATE INDEX type_suite_article_status ON type_suite_articles(status, id)',
        ], $driver !== 'mysql')];
    }
}
